cat > main.yml << 'EOF'
- hosts: all
  become: yes

  tasks:

    - name: Update system
      include_tasks: playbooks/update_system.yml
      when: update_system | default(false)

    - name: Install minicom
      include_tasks: playbooks/install_minicom.yml
      when: install_minicom | default(false)

    - name: Install common tools
      include_tasks: playbooks/common_tools.yml
      when: install_common | default(false)
EOF